(() => {
  const languages = {
    en: { name: "English", locale: "en" },
    tr: { name: "Türkçe", locale: "tr" },
    de: { name: "Deutsch", locale: "de" },
    fr: { name: "Français", locale: "fr" },
    "zh-CN": { name: "简体中文", locale: "zh-CN" },
    it: { name: "Italiano", locale: "it" },
  };

  const catalogs = {
    tr: {
      "Overview": "Genel Bakış", "Sources": "Kaynaklar", "Jobs": "İşler", "Reports": "Raporlar", "Settings": "Ayarlar",
      "Search reports": "Raporlarda ara", "Create job": "İş oluştur", "Local service healthy": "Yerel servis sağlıklı", "Sign out": "Çıkış yap",
      "Your local RAG security and content-quality workspace.": "Yerel RAG güvenliği ve içerik kalitesi çalışma alanınız.",
      "Latest findings": "Son bulgular", "Assessment coverage": "Değerlendirme kapsamı", "Queued work": "Kuyruktaki işler", "Recent reports": "Son raporlar", "Recent jobs": "Son işler",
      "Remember environments without storing secret values.": "Gizli değerleri saklamadan ortamları kaydedin.", "Scan local environment": "Yerel ortamı tara", "Connected sources": "Bağlı kaynaklar", "Add source manually": "Kaynağı elle ekle",
      "Name": "Ad", "Type": "Tür", "Location": "Konum", "Capability": "Yetenek", "Origin": "Köken", "URL or local path": "URL veya yerel yol", "Credential reference (optional)": "Kimlik bilgisi referansı (isteğe bağlı)", "Save source": "Kaynağı kaydet", "Remove": "Kaldır",
      "Create, monitor, cancel, and retry durable local work.": "Kalıcı yerel işleri oluşturun, izleyin, iptal edin ve yeniden deneyin.", "Process one now": "Bir işi şimdi çalıştır", "The machine-wide Host Service normally processes this queue automatically.": "Makine genelindeki Host Service normalde bu kuyruğu otomatik işler.",
      "Analysis": "Analiz", "Status": "Durum", "Progress": "İlerleme", "Attempts": "Deneme", "Created": "Oluşturulma",
      "Every completed job is stored here as a versioned local report—not as a loose HTML file.": "Tamamlanan her iş, bağımsız bir HTML dosyası yerine sürümlü yerel rapor olarak burada saklanır.", "From": "Başlangıç", "To": "Bitiş", "All sources": "Tüm kaynaklar", "Apply filters": "Filtreleri uygula", "Clear": "Temizle", "Select exactly two reports to compare.": "Karşılaştırmak için tam olarak iki rapor seçin.", "Compare selected": "Seçilenleri karşılaştır",
      "Overall score": "Genel puan", "Findings": "Bulgular", "Executive summary": "Yönetici özeti", "Risk interpretation": "Risk yorumu", "Priority actions": "Öncelikli eylemler", "Questions for review": "İnceleme soruları", "Verification steps": "Doğrulama adımları", "Limitations": "Sınırlamalar", "Coverage and ingestion": "Kapsam ve veri alımı", "Evidence": "Kanıt", "Recommendation": "Öneri", "Rule": "Kural", "Remediation": "Düzeltme", "Stage": "Aşama", "Issue": "Sorun",
      "Report comparison": "Rapor karşılaştırması", "New findings": "Yeni bulgular", "Resolved": "Çözülen", "Not observed": "Gözlemlenmeyen", "Recurring": "Tekrarlayan", "Score changes": "Puan değişiklikleri", "Metric": "Ölçüt", "Baseline": "Referans", "Candidate": "Aday", "Change": "Değişim",
      "Machine-local service, privacy, and connector configuration.": "Makine-yerel servis, gizlilik ve bağlayıcı yapılandırması.", "Service": "Servis", "Healthy": "Sağlıklı", "AI providers": "AI sağlayıcıları", "Discovery privacy": "Keşif gizliliği", "Manage sources": "Kaynakları yönet",
      "Saved source": "Kayıtlı kaynak", "Enter details manually": "Bilgileri elle gir", "File or folder": "Dosya veya klasör", "Local path": "Yerel yol", "Queue scan": "Taramayı kuyruğa ekle", "Base URL": "Temel URL", "Credential reference": "Kimlik bilgisi referansı", "Load knowledge bases": "Bilgi tabanlarını yükle", "Knowledge base": "Bilgi tabanı", "Knowledge ID": "Bilgi kimliği",
      "AI-assisted analysis": "AI destekli analiz", "Add AI analysis to this report": "Bu rapora AI analizi ekle", "Provider": "Sağlayıcı", "Model": "Model", "Endpoint": "Uç nokta", "Detect available models": "Kullanılabilir modelleri bul", "The deterministic scan remains authoritative. AI adds a separate advisory interpretation.": "Deterministik tarama asıl sonuçtur. AI ayrı bir danışman yorumu ekler.", "I approve sending the bounded, redacted findings summary to this remote provider.": "Sınırlandırılmış ve maskelenmiş bulgu özetinin bu uzak sağlayıcıya gönderilmesini onaylıyorum.",
      "Machine-local dashboard": "Makine-yerel dashboard", "Sign in": "Giriş yap", "Use the administrator account created during local setup.": "Yerel kurulumda oluşturulan yönetici hesabını kullanın.", "Username": "Kullanıcı adı", "Passphrase": "Parola",
      "Create the local administrator and workspace": "Yerel yöneticiyi ve çalışma alanını oluşturun", "Everything stays on this machine. This account does not create an online identity.": "Her şey bu makinede kalır. Bu hesap çevrimiçi bir kimlik oluşturmaz.", "Local administrator": "Yerel yönetici", "How will you use RAGScanner?": "RAGScanner'ı nasıl kullanacaksınız?", "Web dashboard": "Web dashboard", "Command line": "Komut satırı", "Choose your first source": "İlk kaynağınızı seçin", "Another RAG environment": "Başka bir RAG ortamı", "Temporary folder scan": "Geçici klasör taraması", "Source name": "Kaynak adı", "URL or path": "URL veya yol", "Finish setup": "Kurulumu tamamla", "Administrator": "Yönetici", "Interface": "Arayüz", "First source": "İlk kaynak", "Review": "İnceleme",
    },
    de: {
      "Overview": "Übersicht", "Sources": "Quellen", "Jobs": "Aufträge", "Reports": "Berichte", "Settings": "Einstellungen", "Search reports": "Berichte durchsuchen", "Create job": "Auftrag erstellen", "Local service healthy": "Lokaler Dienst fehlerfrei", "Sign out": "Abmelden",
      "Your local RAG security and content-quality workspace.": "Ihr lokaler Arbeitsbereich für RAG-Sicherheit und Inhaltsqualität.", "Latest findings": "Neueste Befunde", "Assessment coverage": "Prüfabdeckung", "Queued work": "Wartende Aufträge", "Recent reports": "Neueste Berichte", "Recent jobs": "Neueste Aufträge",
      "Remember environments without storing secret values.": "Umgebungen speichern, ohne Geheimnisse abzulegen.", "Scan local environment": "Lokale Umgebung scannen", "Connected sources": "Verbundene Quellen", "Add source manually": "Quelle manuell hinzufügen", "Name": "Name", "Type": "Typ", "Location": "Ort", "Capability": "Fähigkeit", "Origin": "Ursprung", "URL or local path": "URL oder lokaler Pfad", "Credential reference (optional)": "Anmeldedaten-Referenz (optional)", "Save source": "Quelle speichern", "Remove": "Entfernen",
      "Create, monitor, cancel, and retry durable local work.": "Dauerhafte lokale Aufträge erstellen, überwachen, abbrechen und wiederholen.", "Process one now": "Einen jetzt verarbeiten", "Analysis": "Analyse", "Status": "Status", "Progress": "Fortschritt", "Attempts": "Versuche", "Created": "Erstellt",
      "From": "Von", "To": "Bis", "All sources": "Alle Quellen", "Apply filters": "Filter anwenden", "Clear": "Zurücksetzen", "Select exactly two reports to compare.": "Wählen Sie genau zwei Berichte zum Vergleich.", "Compare selected": "Auswahl vergleichen",
      "Overall score": "Gesamtbewertung", "Findings": "Befunde", "Executive summary": "Zusammenfassung", "Risk interpretation": "Risikobewertung", "Priority actions": "Priorisierte Maßnahmen", "Questions for review": "Prüffragen", "Verification steps": "Prüfschritte", "Limitations": "Einschränkungen", "Coverage and ingestion": "Abdeckung und Aufnahme", "Evidence": "Nachweis", "Recommendation": "Empfehlung", "Rule": "Regel", "Remediation": "Behebung", "Stage": "Phase", "Issue": "Problem",
      "Report comparison": "Berichtsvergleich", "New findings": "Neue Befunde", "Resolved": "Behoben", "Not observed": "Nicht beobachtet", "Recurring": "Wiederkehrend", "Score changes": "Bewertungsänderungen", "Metric": "Metrik", "Baseline": "Ausgangswert", "Candidate": "Kandidat", "Change": "Änderung",
      "Machine-local service, privacy, and connector configuration.": "Rechnerlokale Dienst-, Datenschutz- und Connector-Konfiguration.", "Service": "Dienst", "Healthy": "Fehlerfrei", "AI providers": "KI-Anbieter", "Discovery privacy": "Datenschutz bei Erkennung", "Manage sources": "Quellen verwalten",
      "Saved source": "Gespeicherte Quelle", "Enter details manually": "Details manuell eingeben", "File or folder": "Datei oder Ordner", "Local path": "Lokaler Pfad", "Queue scan": "Scan einreihen", "Base URL": "Basis-URL", "Credential reference": "Anmeldedaten-Referenz", "Load knowledge bases": "Wissensdatenbanken laden", "Knowledge base": "Wissensdatenbank", "Knowledge ID": "Wissens-ID",
      "AI-assisted analysis": "KI-gestützte Analyse", "Add AI analysis to this report": "KI-Analyse zu diesem Bericht hinzufügen", "Provider": "Anbieter", "Model": "Modell", "Endpoint": "Endpunkt", "Detect available models": "Verfügbare Modelle erkennen", "The deterministic scan remains authoritative. AI adds a separate advisory interpretation.": "Der deterministische Scan bleibt maßgeblich. KI ergänzt eine separate beratende Interpretation.", "I approve sending the bounded, redacted findings summary to this remote provider.": "Ich stimme der Übertragung der begrenzten, geschwärzten Befundzusammenfassung an diesen externen Anbieter zu.",
      "Machine-local dashboard": "Rechnerlokales Dashboard", "Sign in": "Anmelden", "Use the administrator account created during local setup.": "Verwenden Sie das bei der lokalen Einrichtung erstellte Administratorkonto.", "Username": "Benutzername", "Passphrase": "Passphrase", "Create the local administrator and workspace": "Lokalen Administrator und Arbeitsbereich erstellen", "Everything stays on this machine. This account does not create an online identity.": "Alles bleibt auf diesem Rechner. Dieses Konto erstellt keine Online-Identität.", "Local administrator": "Lokaler Administrator", "How will you use RAGScanner?": "Wie möchten Sie RAGScanner verwenden?", "Web dashboard": "Web-Dashboard", "Command line": "Befehlszeile", "Choose your first source": "Erste Quelle auswählen", "Another RAG environment": "Andere RAG-Umgebung", "Temporary folder scan": "Temporärer Ordnerscan", "Source name": "Quellenname", "URL or path": "URL oder Pfad", "Finish setup": "Einrichtung abschließen", "Administrator": "Administrator", "Interface": "Oberfläche", "First source": "Erste Quelle", "Review": "Prüfen",
    },
    fr: {
      "Overview": "Vue d’ensemble", "Sources": "Sources", "Jobs": "Tâches", "Reports": "Rapports", "Settings": "Paramètres", "Search reports": "Rechercher des rapports", "Create job": "Créer une tâche", "Local service healthy": "Service local opérationnel", "Sign out": "Se déconnecter",
      "Your local RAG security and content-quality workspace.": "Votre espace local de sécurité RAG et de qualité du contenu.", "Latest findings": "Derniers constats", "Assessment coverage": "Couverture de l’évaluation", "Queued work": "Travaux en attente", "Recent reports": "Rapports récents", "Recent jobs": "Tâches récentes",
      "Remember environments without storing secret values.": "Enregistrez les environnements sans stocker de secrets.", "Scan local environment": "Analyser l’environnement local", "Connected sources": "Sources connectées", "Add source manually": "Ajouter une source manuellement", "Name": "Nom", "Type": "Type", "Location": "Emplacement", "Capability": "Capacité", "Origin": "Origine", "URL or local path": "URL ou chemin local", "Credential reference (optional)": "Référence d’identifiants (facultatif)", "Save source": "Enregistrer la source", "Remove": "Supprimer",
      "Create, monitor, cancel, and retry durable local work.": "Créez, surveillez, annulez et relancez les tâches locales persistantes.", "Process one now": "Traiter une tâche maintenant", "Analysis": "Analyse", "Status": "État", "Progress": "Progression", "Attempts": "Tentatives", "Created": "Créée",
      "From": "Du", "To": "Au", "All sources": "Toutes les sources", "Apply filters": "Appliquer les filtres", "Clear": "Effacer", "Select exactly two reports to compare.": "Sélectionnez exactement deux rapports à comparer.", "Compare selected": "Comparer la sélection",
      "Overall score": "Score global", "Findings": "Constats", "Executive summary": "Résumé exécutif", "Risk interpretation": "Interprétation du risque", "Priority actions": "Actions prioritaires", "Questions for review": "Questions de contrôle", "Verification steps": "Étapes de vérification", "Limitations": "Limites", "Coverage and ingestion": "Couverture et ingestion", "Evidence": "Preuve", "Recommendation": "Recommandation", "Rule": "Règle", "Remediation": "Correction", "Stage": "Étape", "Issue": "Problème",
      "Report comparison": "Comparaison des rapports", "New findings": "Nouveaux constats", "Resolved": "Résolus", "Not observed": "Non observés", "Recurring": "Récurrents", "Score changes": "Évolution des scores", "Metric": "Mesure", "Baseline": "Référence", "Candidate": "Candidat", "Change": "Évolution",
      "Machine-local service, privacy, and connector configuration.": "Configuration locale du service, de la confidentialité et des connecteurs.", "Service": "Service", "Healthy": "Opérationnel", "AI providers": "Fournisseurs d’IA", "Discovery privacy": "Confidentialité de la découverte", "Manage sources": "Gérer les sources",
      "Saved source": "Source enregistrée", "Enter details manually": "Saisir les détails", "File or folder": "Fichier ou dossier", "Local path": "Chemin local", "Queue scan": "Mettre l’analyse en file", "Base URL": "URL de base", "Credential reference": "Référence d’identifiants", "Load knowledge bases": "Charger les bases de connaissances", "Knowledge base": "Base de connaissances", "Knowledge ID": "ID de connaissance",
      "AI-assisted analysis": "Analyse assistée par IA", "Add AI analysis to this report": "Ajouter une analyse IA à ce rapport", "Provider": "Fournisseur", "Model": "Modèle", "Endpoint": "Point de terminaison", "Detect available models": "Détecter les modèles disponibles", "The deterministic scan remains authoritative. AI adds a separate advisory interpretation.": "L’analyse déterministe reste la référence. L’IA ajoute une interprétation consultative distincte.", "I approve sending the bounded, redacted findings summary to this remote provider.": "J’autorise l’envoi du résumé limité et expurgé des constats à ce fournisseur distant.",
      "Machine-local dashboard": "Tableau de bord local", "Sign in": "Se connecter", "Use the administrator account created during local setup.": "Utilisez le compte administrateur créé lors de la configuration locale.", "Username": "Nom d’utilisateur", "Passphrase": "Phrase secrète", "Create the local administrator and workspace": "Créer l’administrateur local et l’espace de travail", "Everything stays on this machine. This account does not create an online identity.": "Tout reste sur cette machine. Ce compte ne crée pas d’identité en ligne.", "Local administrator": "Administrateur local", "How will you use RAGScanner?": "Comment utiliserez-vous RAGScanner ?", "Web dashboard": "Tableau de bord web", "Command line": "Ligne de commande", "Choose your first source": "Choisissez votre première source", "Another RAG environment": "Autre environnement RAG", "Temporary folder scan": "Analyse temporaire d’un dossier", "Source name": "Nom de la source", "URL or path": "URL ou chemin", "Finish setup": "Terminer la configuration", "Administrator": "Administrateur", "Interface": "Interface", "First source": "Première source", "Review": "Vérification",
    },
    "zh-CN": {
      "Overview": "概览", "Sources": "数据源", "Jobs": "任务", "Reports": "报告", "Settings": "设置", "Search reports": "搜索报告", "Create job": "创建任务", "Local service healthy": "本地服务运行正常", "Sign out": "退出登录",
      "Your local RAG security and content-quality workspace.": "您的本地 RAG 安全与内容质量工作区。", "Latest findings": "最新发现", "Assessment coverage": "评估覆盖率", "Queued work": "排队任务", "Recent reports": "最近报告", "Recent jobs": "最近任务",
      "Remember environments without storing secret values.": "记录环境信息但不存储机密值。", "Scan local environment": "扫描本地环境", "Connected sources": "已连接数据源", "Add source manually": "手动添加数据源", "Name": "名称", "Type": "类型", "Location": "位置", "Capability": "能力", "Origin": "来源", "URL or local path": "URL 或本地路径", "Credential reference (optional)": "凭据引用（可选）", "Save source": "保存数据源", "Remove": "移除",
      "Create, monitor, cancel, and retry durable local work.": "创建、监控、取消和重试持久化本地任务。", "Process one now": "立即处理一项", "Analysis": "分析", "Status": "状态", "Progress": "进度", "Attempts": "尝试次数", "Created": "创建时间",
      "From": "从", "To": "至", "All sources": "所有数据源", "Apply filters": "应用筛选", "Clear": "清除", "Select exactly two reports to compare.": "请选择两份报告进行比较。", "Compare selected": "比较所选报告",
      "Overall score": "总分", "Findings": "发现", "Executive summary": "执行摘要", "Risk interpretation": "风险解读", "Priority actions": "优先操作", "Questions for review": "审核问题", "Verification steps": "验证步骤", "Limitations": "局限性", "Coverage and ingestion": "覆盖与摄取", "Evidence": "证据", "Recommendation": "建议", "Rule": "规则", "Remediation": "修复", "Stage": "阶段", "Issue": "问题",
      "Report comparison": "报告比较", "New findings": "新发现", "Resolved": "已解决", "Not observed": "未观察到", "Recurring": "重复出现", "Score changes": "分数变化", "Metric": "指标", "Baseline": "基准", "Candidate": "候选", "Change": "变化",
      "Machine-local service, privacy, and connector configuration.": "本机服务、隐私和连接器配置。", "Service": "服务", "Healthy": "正常", "AI providers": "AI 提供商", "Discovery privacy": "发现隐私", "Manage sources": "管理数据源",
      "Saved source": "已保存数据源", "Enter details manually": "手动输入详细信息", "File or folder": "文件或文件夹", "Local path": "本地路径", "Queue scan": "加入扫描队列", "Base URL": "基础 URL", "Credential reference": "凭据引用", "Load knowledge bases": "加载知识库", "Knowledge base": "知识库", "Knowledge ID": "知识 ID",
      "AI-assisted analysis": "AI 辅助分析", "Add AI analysis to this report": "为此报告添加 AI 分析", "Provider": "提供商", "Model": "模型", "Endpoint": "端点", "Detect available models": "检测可用模型", "The deterministic scan remains authoritative. AI adds a separate advisory interpretation.": "确定性扫描仍是权威结果；AI 仅添加独立的辅助解读。", "I approve sending the bounded, redacted findings summary to this remote provider.": "我同意将有限且已脱敏的发现摘要发送给此远程提供商。",
      "Machine-local dashboard": "本机仪表板", "Sign in": "登录", "Use the administrator account created during local setup.": "请使用本地设置期间创建的管理员账户。", "Username": "用户名", "Passphrase": "密码短语", "Create the local administrator and workspace": "创建本地管理员和工作区", "Everything stays on this machine. This account does not create an online identity.": "所有内容都保留在此计算机上，该账户不会创建在线身份。", "Local administrator": "本地管理员", "How will you use RAGScanner?": "您将如何使用 RAGScanner？", "Web dashboard": "Web 仪表板", "Command line": "命令行", "Choose your first source": "选择第一个数据源", "Another RAG environment": "其他 RAG 环境", "Temporary folder scan": "临时文件夹扫描", "Source name": "数据源名称", "URL or path": "URL 或路径", "Finish setup": "完成设置", "Administrator": "管理员", "Interface": "界面", "First source": "第一个数据源", "Review": "检查",
    },
    it: {
      "Overview": "Panoramica", "Sources": "Origini", "Jobs": "Attività", "Reports": "Rapporti", "Settings": "Impostazioni", "Search reports": "Cerca rapporti", "Create job": "Crea attività", "Local service healthy": "Servizio locale operativo", "Sign out": "Esci",
      "Your local RAG security and content-quality workspace.": "Il tuo spazio locale per la sicurezza RAG e la qualità dei contenuti.", "Latest findings": "Risultati recenti", "Assessment coverage": "Copertura della valutazione", "Queued work": "Lavori in coda", "Recent reports": "Rapporti recenti", "Recent jobs": "Attività recenti",
      "Remember environments without storing secret values.": "Memorizza gli ambienti senza salvare valori segreti.", "Scan local environment": "Analizza l’ambiente locale", "Connected sources": "Origini connesse", "Add source manually": "Aggiungi origine manualmente", "Name": "Nome", "Type": "Tipo", "Location": "Posizione", "Capability": "Capacità", "Origin": "Origine", "URL or local path": "URL o percorso locale", "Credential reference (optional)": "Riferimento credenziali (facoltativo)", "Save source": "Salva origine", "Remove": "Rimuovi",
      "Create, monitor, cancel, and retry durable local work.": "Crea, monitora, annulla e riprova attività locali persistenti.", "Process one now": "Elabora ora", "Analysis": "Analisi", "Status": "Stato", "Progress": "Avanzamento", "Attempts": "Tentativi", "Created": "Creata",
      "From": "Da", "To": "A", "All sources": "Tutte le origini", "Apply filters": "Applica filtri", "Clear": "Cancella", "Select exactly two reports to compare.": "Seleziona esattamente due rapporti da confrontare.", "Compare selected": "Confronta selezionati",
      "Overall score": "Punteggio complessivo", "Findings": "Risultati", "Executive summary": "Sintesi esecutiva", "Risk interpretation": "Interpretazione del rischio", "Priority actions": "Azioni prioritarie", "Questions for review": "Domande di revisione", "Verification steps": "Passaggi di verifica", "Limitations": "Limitazioni", "Coverage and ingestion": "Copertura e acquisizione", "Evidence": "Evidenza", "Recommendation": "Raccomandazione", "Rule": "Regola", "Remediation": "Correzione", "Stage": "Fase", "Issue": "Problema",
      "Report comparison": "Confronto rapporti", "New findings": "Nuovi risultati", "Resolved": "Risolti", "Not observed": "Non osservati", "Recurring": "Ricorrenti", "Score changes": "Variazioni punteggio", "Metric": "Metrica", "Baseline": "Riferimento", "Candidate": "Candidato", "Change": "Variazione",
      "Machine-local service, privacy, and connector configuration.": "Configurazione locale di servizio, privacy e connettori.", "Service": "Servizio", "Healthy": "Operativo", "AI providers": "Provider AI", "Discovery privacy": "Privacy del rilevamento", "Manage sources": "Gestisci origini",
      "Saved source": "Origine salvata", "Enter details manually": "Inserisci i dettagli", "File or folder": "File o cartella", "Local path": "Percorso locale", "Queue scan": "Accoda analisi", "Base URL": "URL base", "Credential reference": "Riferimento credenziali", "Load knowledge bases": "Carica basi di conoscenza", "Knowledge base": "Base di conoscenza", "Knowledge ID": "ID conoscenza",
      "AI-assisted analysis": "Analisi assistita da AI", "Add AI analysis to this report": "Aggiungi analisi AI al rapporto", "Provider": "Provider", "Model": "Modello", "Endpoint": "Endpoint", "Detect available models": "Rileva modelli disponibili", "The deterministic scan remains authoritative. AI adds a separate advisory interpretation.": "L’analisi deterministica resta autorevole. L’AI aggiunge un’interpretazione consultiva separata.", "I approve sending the bounded, redacted findings summary to this remote provider.": "Autorizzo l’invio del riepilogo limitato e oscurato dei risultati a questo provider remoto.",
      "Machine-local dashboard": "Dashboard locale", "Sign in": "Accedi", "Use the administrator account created during local setup.": "Usa l’account amministratore creato durante la configurazione locale.", "Username": "Nome utente", "Passphrase": "Passphrase", "Create the local administrator and workspace": "Crea l’amministratore locale e lo spazio di lavoro", "Everything stays on this machine. This account does not create an online identity.": "Tutto rimane su questa macchina. Questo account non crea un’identità online.", "Local administrator": "Amministratore locale", "How will you use RAGScanner?": "Come userai RAGScanner?", "Web dashboard": "Dashboard web", "Command line": "Riga di comando", "Choose your first source": "Scegli la prima origine", "Another RAG environment": "Altro ambiente RAG", "Temporary folder scan": "Analisi temporanea cartella", "Source name": "Nome origine", "URL or path": "URL o percorso", "Finish setup": "Completa configurazione", "Administrator": "Amministratore", "Interface": "Interfaccia", "First source": "Prima origine", "Review": "Revisione",
    },
  };

  Object.assign(catalogs.tr, {
    "Language": "Dil", "Report": "Rapor", "Source": "Kaynak", "Run date": "Çalışma tarihi", "Score": "Puan", "Job": "İş", "No scans yet": "Henüz tarama yok", "Assessed and partially assessed checks": "Değerlendirilen ve kısmen değerlendirilen kontroller", "The Host Service processes jobs continuously": "Host Service işleri sürekli işler", "No reports match this view.": "Bu görünüme uyan rapor yok.", "No jobs yet.": "Henüz iş yok.", "View all": "Tümünü görüntüle", "enabled profile(s)": "etkin profil", "total": "toplam", "Select": "Seç", "Use details": "Bilgileri kullan", "Scanning bounded local service metadata…": "Sınırlandırılmış yerel servis metadatası taranıyor…", "environment candidate(s) found.": "ortam adayı bulundu.", "No supported local environment candidate was found.": "Desteklenen bir yerel ortam adayı bulunamadı.", "Discovery failed.": "Keşif başarısız oldu.", "Enter an OpenWebUI URL and credential reference first.": "Önce OpenWebUI URL'sini ve kimlik bilgisi referansını girin.", "Loading accessible OpenWebUI knowledge bases…": "Erişilebilir OpenWebUI bilgi tabanları yükleniyor…", "Select a knowledge base": "Bilgi tabanı seçin", "knowledge base(s) loaded.": "bilgi tabanı yüklendi.", "Knowledge-base discovery failed.": "Bilgi tabanı keşfi başarısız oldu.", "Local providers keep the bounded, redacted analysis context on this machine.": "Yerel sağlayıcılar sınırlandırılmış ve maskelenmiş analiz bağlamını bu makinede tutar.", "Remote providers receive only a bounded, redacted findings summary—never raw documents or finding evidence.": "Uzak sağlayıcılar yalnızca sınırlandırılmış ve maskelenmiş bulgu özetini alır; ham belgeleri veya bulgu kanıtlarını asla almaz.", "Detecting models…": "Modeller aranıyor…", "model(s) found": "model bulundu", "No models found": "Model bulunamadı", "Model discovery failed": "Model keşfi başarısız oldu", "The request could not be completed.": "İstek tamamlanamadı.",
  });
  Object.assign(catalogs.de, {
    "Language": "Sprache", "Report": "Bericht", "Source": "Quelle", "Run date": "Ausführungsdatum", "Score": "Bewertung", "Job": "Auftrag", "No scans yet": "Noch keine Scans", "Assessed and partially assessed checks": "Geprüfte und teilweise geprüfte Kontrollen", "The Host Service processes jobs continuously": "Der Host Service verarbeitet Aufträge fortlaufend", "No reports match this view.": "Keine Berichte entsprechen dieser Ansicht.", "No jobs yet.": "Noch keine Aufträge.", "View all": "Alle anzeigen", "enabled profile(s)": "aktive Profile", "total": "gesamt", "Select": "Auswählen", "Use details": "Details verwenden", "Scanning bounded local service metadata…": "Begrenzte lokale Dienstmetadaten werden gescannt…", "environment candidate(s) found.": "Umgebungskandidat(en) gefunden.", "No supported local environment candidate was found.": "Kein unterstützter lokaler Umgebungskandidat gefunden.", "Discovery failed.": "Erkennung fehlgeschlagen.", "Enter an OpenWebUI URL and credential reference first.": "Geben Sie zuerst eine OpenWebUI-URL und eine Anmeldedaten-Referenz ein.", "Loading accessible OpenWebUI knowledge bases…": "Verfügbare OpenWebUI-Wissensdatenbanken werden geladen…", "Select a knowledge base": "Wissensdatenbank auswählen", "knowledge base(s) loaded.": "Wissensdatenbank(en) geladen.", "Knowledge-base discovery failed.": "Wissensdatenbank-Erkennung fehlgeschlagen.", "Local providers keep the bounded, redacted analysis context on this machine.": "Lokale Anbieter behalten den begrenzten, geschwärzten Analysekontext auf diesem Rechner.", "Remote providers receive only a bounded, redacted findings summary—never raw documents or finding evidence.": "Externe Anbieter erhalten nur eine begrenzte, geschwärzte Befundzusammenfassung – niemals Rohdokumente oder Befundnachweise.", "Detecting models…": "Modelle werden erkannt…", "model(s) found": "Modell(e) gefunden", "No models found": "Keine Modelle gefunden", "Model discovery failed": "Modellerkennung fehlgeschlagen", "The request could not be completed.": "Die Anfrage konnte nicht abgeschlossen werden.",
  });
  Object.assign(catalogs.fr, {
    "Language": "Langue", "Report": "Rapport", "Source": "Source", "Run date": "Date d’exécution", "Score": "Score", "Job": "Tâche", "No scans yet": "Aucune analyse", "Assessed and partially assessed checks": "Contrôles évalués et partiellement évalués", "The Host Service processes jobs continuously": "Le Host Service traite les tâches en continu", "No reports match this view.": "Aucun rapport ne correspond à cette vue.", "No jobs yet.": "Aucune tâche.", "View all": "Tout afficher", "enabled profile(s)": "profils actifs", "total": "total", "Select": "Sélectionner", "Use details": "Utiliser les détails", "Scanning bounded local service metadata…": "Analyse limitée des métadonnées des services locaux…", "environment candidate(s) found.": "environnement(s) candidat(s) trouvé(s).", "No supported local environment candidate was found.": "Aucun environnement local pris en charge n’a été trouvé.", "Discovery failed.": "La découverte a échoué.", "Enter an OpenWebUI URL and credential reference first.": "Saisissez d’abord l’URL OpenWebUI et la référence d’identifiants.", "Loading accessible OpenWebUI knowledge bases…": "Chargement des bases de connaissances OpenWebUI accessibles…", "Select a knowledge base": "Sélectionner une base de connaissances", "knowledge base(s) loaded.": "base(s) de connaissances chargée(s).", "Knowledge-base discovery failed.": "La découverte des bases de connaissances a échoué.", "Local providers keep the bounded, redacted analysis context on this machine.": "Les fournisseurs locaux conservent le contexte d’analyse limité et expurgé sur cette machine.", "Remote providers receive only a bounded, redacted findings summary—never raw documents or finding evidence.": "Les fournisseurs distants ne reçoivent qu’un résumé limité et expurgé, jamais les documents bruts ni les preuves.", "Detecting models…": "Détection des modèles…", "model(s) found": "modèle(s) trouvé(s)", "No models found": "Aucun modèle trouvé", "Model discovery failed": "La découverte des modèles a échoué", "The request could not be completed.": "La requête n’a pas pu être terminée.",
  });
  Object.assign(catalogs["zh-CN"], {
    "Language": "语言", "Report": "报告", "Source": "数据源", "Run date": "运行日期", "Score": "分数", "Job": "任务", "No scans yet": "暂无扫描", "Assessed and partially assessed checks": "已评估和部分评估的检查", "The Host Service processes jobs continuously": "Host Service 持续处理任务", "No reports match this view.": "没有符合此视图的报告。", "No jobs yet.": "暂无任务。", "View all": "查看全部", "enabled profile(s)": "个已启用配置", "total": "总计", "Select": "选择", "Use details": "使用详细信息", "Scanning bounded local service metadata…": "正在扫描有限的本地服务元数据…", "environment candidate(s) found.": "个候选环境已找到。", "No supported local environment candidate was found.": "未找到受支持的本地候选环境。", "Discovery failed.": "发现失败。", "Enter an OpenWebUI URL and credential reference first.": "请先输入 OpenWebUI URL 和凭据引用。", "Loading accessible OpenWebUI knowledge bases…": "正在加载可访问的 OpenWebUI 知识库…", "Select a knowledge base": "选择知识库", "knowledge base(s) loaded.": "个知识库已加载。", "Knowledge-base discovery failed.": "知识库发现失败。", "Local providers keep the bounded, redacted analysis context on this machine.": "本地提供商会将有限且已脱敏的分析上下文保留在此计算机上。", "Remote providers receive only a bounded, redacted findings summary—never raw documents or finding evidence.": "远程提供商仅接收有限且已脱敏的发现摘要，绝不会收到原始文档或发现证据。", "Detecting models…": "正在检测模型…", "model(s) found": "个模型已找到", "No models found": "未找到模型", "Model discovery failed": "模型发现失败", "The request could not be completed.": "无法完成请求。",
  });
  Object.assign(catalogs.it, {
    "Language": "Lingua", "Report": "Rapporto", "Source": "Origine", "Run date": "Data esecuzione", "Score": "Punteggio", "Job": "Attività", "No scans yet": "Nessuna analisi", "Assessed and partially assessed checks": "Controlli valutati e parzialmente valutati", "The Host Service processes jobs continuously": "Host Service elabora continuamente le attività", "No reports match this view.": "Nessun rapporto corrisponde a questa vista.", "No jobs yet.": "Nessuna attività.", "View all": "Mostra tutto", "enabled profile(s)": "profili attivi", "total": "totale", "Select": "Seleziona", "Use details": "Usa dettagli", "Scanning bounded local service metadata…": "Analisi limitata dei metadati dei servizi locali…", "environment candidate(s) found.": "ambienti candidati trovati.", "No supported local environment candidate was found.": "Nessun ambiente locale supportato trovato.", "Discovery failed.": "Rilevamento non riuscito.", "Enter an OpenWebUI URL and credential reference first.": "Inserisci prima l’URL OpenWebUI e il riferimento credenziali.", "Loading accessible OpenWebUI knowledge bases…": "Caricamento delle basi di conoscenza OpenWebUI accessibili…", "Select a knowledge base": "Seleziona una base di conoscenza", "knowledge base(s) loaded.": "basi di conoscenza caricate.", "Knowledge-base discovery failed.": "Rilevamento delle basi di conoscenza non riuscito.", "Local providers keep the bounded, redacted analysis context on this machine.": "I provider locali mantengono su questa macchina il contesto di analisi limitato e oscurato.", "Remote providers receive only a bounded, redacted findings summary—never raw documents or finding evidence.": "I provider remoti ricevono solo un riepilogo limitato e oscurato, mai documenti grezzi o evidenze.", "Detecting models…": "Rilevamento modelli…", "model(s) found": "modelli trovati", "No models found": "Nessun modello trovato", "Model discovery failed": "Rilevamento modelli non riuscito", "The request could not be completed.": "Impossibile completare la richiesta.",
  });
  Object.assign(catalogs.tr, {
    "Choose what to scan. Connection details appear only when the selected source needs them.": "Neyi tarayacağınızı seçin. Bağlantı bilgileri yalnızca seçilen kaynak gerektiriyorsa gösterilir.", "Choose a saved source or enter a path manually.": "Kayıtlı bir kaynak seçin veya yolu elle girin.", "Choose the file or folder this scan should assess.": "Bu taramanın değerlendireceği dosya veya klasörü seçin.", "Select one accessible OpenWebUI knowledge base.": "Erişilebilir bir OpenWebUI bilgi tabanı seçin.", "The path must be readable by the machine-wide service account.": "Yol, makine genelindeki servis hesabı tarafından okunabilmelidir.", "Connect a source to load knowledge bases": "Bilgi tabanlarını yüklemek için bir kaynak bağlayın", "Known environments use safe defaults. Choose Custom only when you need to enter every connection detail yourself.": "Bilinen ortamlar güvenli varsayılanları kullanır. Tüm bağlantı bilgilerini kendiniz girecekseniz Custom seçin.", "Ready to scan:": "Taramaya hazır:", "RAGScanner can inventory OpenWebUI knowledge bases and scan their content.": "RAGScanner OpenWebUI bilgi tabanlarını listeleyebilir ve içeriklerini tarayabilir.", "The value is kept only in the running machine service memory. It is never written to SQLite, reports, or jobs.": "Değer yalnızca çalışan makine servisinin belleğinde tutulur; SQLite'a, raporlara veya işlere yazılmaz.", "1 · Choose an environment": "1 · Ortam seçin",
  });
  Object.assign(catalogs.de, {
    "Choose what to scan. Connection details appear only when the selected source needs them.": "Wählen Sie, was gescannt werden soll. Verbindungsdetails erscheinen nur bei Bedarf.", "Choose a saved source or enter a path manually.": "Gespeicherte Quelle wählen oder Pfad manuell eingeben.", "Choose the file or folder this scan should assess.": "Datei oder Ordner für diesen Scan auswählen.", "Select one accessible OpenWebUI knowledge base.": "Eine zugängliche OpenWebUI-Wissensdatenbank auswählen.", "The path must be readable by the machine-wide service account.": "Der Pfad muss für das rechnerweite Dienstkonto lesbar sein.", "Connect a source to load knowledge bases": "Quelle verbinden, um Wissensdatenbanken zu laden", "Known environments use safe defaults. Choose Custom only when you need to enter every connection detail yourself.": "Bekannte Umgebungen verwenden sichere Standardwerte. Wählen Sie Benutzerdefiniert nur für eigene Verbindungsdetails.", "Ready to scan:": "Scanbereit:", "RAGScanner can inventory OpenWebUI knowledge bases and scan their content.": "RAGScanner kann OpenWebUI-Wissensdatenbanken auflisten und deren Inhalt scannen.", "The value is kept only in the running machine service memory. It is never written to SQLite, reports, or jobs.": "Der Wert bleibt nur im Speicher des laufenden Rechnerdienstes und wird nie in SQLite, Berichte oder Aufträge geschrieben.", "1 · Choose an environment": "1 · Umgebung auswählen",
  });
  Object.assign(catalogs.fr, {
    "Choose what to scan. Connection details appear only when the selected source needs them.": "Choisissez quoi analyser. Les détails de connexion n’apparaissent que si nécessaire.", "Choose a saved source or enter a path manually.": "Choisissez une source enregistrée ou saisissez un chemin.", "Choose the file or folder this scan should assess.": "Choisissez le fichier ou dossier à évaluer.", "Select one accessible OpenWebUI knowledge base.": "Sélectionnez une base de connaissances OpenWebUI accessible.", "The path must be readable by the machine-wide service account.": "Le chemin doit être lisible par le compte de service de la machine.", "Connect a source to load knowledge bases": "Connectez une source pour charger les bases de connaissances", "Known environments use safe defaults. Choose Custom only when you need to enter every connection detail yourself.": "Les environnements connus utilisent des valeurs sûres. Choisissez Personnalisé uniquement pour saisir tous les détails.", "Ready to scan:": "Prête à analyser :", "RAGScanner can inventory OpenWebUI knowledge bases and scan their content.": "RAGScanner peut répertorier les bases OpenWebUI et analyser leur contenu.", "The value is kept only in the running machine service memory. It is never written to SQLite, reports, or jobs.": "La valeur reste uniquement en mémoire du service actif et n’est jamais écrite dans SQLite, les rapports ou les tâches.", "1 · Choose an environment": "1 · Choisir un environnement",
  });
  Object.assign(catalogs["zh-CN"], {
    "Choose what to scan. Connection details appear only when the selected source needs them.": "选择要扫描的内容；仅在数据源需要时显示连接信息。", "Choose a saved source or enter a path manually.": "选择已保存的数据源或手动输入路径。", "Choose the file or folder this scan should assess.": "选择此次扫描要评估的文件或文件夹。", "Select one accessible OpenWebUI knowledge base.": "选择一个可访问的 OpenWebUI 知识库。", "The path must be readable by the machine-wide service account.": "本机服务账户必须能够读取该路径。", "Connect a source to load knowledge bases": "连接数据源以加载知识库", "Known environments use safe defaults. Choose Custom only when you need to enter every connection detail yourself.": "已知环境使用安全默认值。仅在需要自行输入全部连接信息时选择自定义。", "Ready to scan:": "可扫描：", "RAGScanner can inventory OpenWebUI knowledge bases and scan their content.": "RAGScanner 可以列出 OpenWebUI 知识库并扫描其内容。", "The value is kept only in the running machine service memory. It is never written to SQLite, reports, or jobs.": "该值仅保存在运行中的本机服务内存中，绝不会写入 SQLite、报告或任务。", "1 · Choose an environment": "1 · 选择环境",
  });
  Object.assign(catalogs.it, {
    "Choose what to scan. Connection details appear only when the selected source needs them.": "Scegli cosa analizzare. I dettagli di connessione appaiono solo quando servono.", "Choose a saved source or enter a path manually.": "Scegli un’origine salvata o inserisci un percorso.", "Choose the file or folder this scan should assess.": "Scegli il file o la cartella da valutare.", "Select one accessible OpenWebUI knowledge base.": "Seleziona una knowledge base OpenWebUI accessibile.", "The path must be readable by the machine-wide service account.": "Il percorso deve essere leggibile dall’account del servizio di macchina.", "Connect a source to load knowledge bases": "Connetti un’origine per caricare le knowledge base", "Known environments use safe defaults. Choose Custom only when you need to enter every connection detail yourself.": "Gli ambienti noti usano valori sicuri. Scegli Personalizzato solo per inserire tutti i dettagli.", "Ready to scan:": "Pronta per l’analisi:", "RAGScanner can inventory OpenWebUI knowledge bases and scan their content.": "RAGScanner può elencare le knowledge base OpenWebUI e analizzarne il contenuto.", "The value is kept only in the running machine service memory. It is never written to SQLite, reports, or jobs.": "Il valore resta solo nella memoria del servizio attivo e non viene mai scritto in SQLite, rapporti o attività.", "1 · Choose an environment": "1 · Scegli un ambiente",
  });

  Object.assign(catalogs.tr, {
    "Credential environment-variable reference (optional)": "Kimlik bilgisi ortam değişkeni referansı (isteğe bağlı)",
    "Enter env:OPENWEBUI_API_KEY—not the API key itself. You can also leave this blank and connect later.": "API anahtarının kendisini değil env:OPENWEBUI_API_KEY gibi bir referans girin. Bu alanı boş bırakıp daha sonra da bağlanabilirsiniz.",
    "Enter an environment-variable reference such as env:OPENWEBUI_API_KEY, not the API key itself. You can leave this field blank and connect the source later.": "API anahtarının kendisini değil env:OPENWEBUI_API_KEY gibi bir ortam değişkeni referansı girin. Bu alanı boş bırakıp kaynağı daha sonra bağlayabilirsiniz.",
  });
  Object.assign(catalogs.de, {
    "Credential environment-variable reference (optional)": "Umgebungsvariablen-Referenz für Anmeldedaten (optional)",
    "Enter env:OPENWEBUI_API_KEY—not the API key itself. You can also leave this blank and connect later.": "Geben Sie eine Referenz wie env:OPENWEBUI_API_KEY ein, nicht den API-Schlüssel selbst. Sie können das Feld auch leer lassen und die Verbindung später herstellen.",
    "Enter an environment-variable reference such as env:OPENWEBUI_API_KEY, not the API key itself. You can leave this field blank and connect the source later.": "Geben Sie eine Umgebungsvariablen-Referenz wie env:OPENWEBUI_API_KEY ein, nicht den API-Schlüssel selbst. Sie können das Feld leer lassen und die Quelle später verbinden.",
  });
  Object.assign(catalogs.fr, {
    "Credential environment-variable reference (optional)": "Référence de variable d’environnement pour les identifiants (facultatif)",
    "Enter env:OPENWEBUI_API_KEY—not the API key itself. You can also leave this blank and connect later.": "Saisissez une référence telle que env:OPENWEBUI_API_KEY, et non la clé API elle-même. Vous pouvez aussi laisser ce champ vide et vous connecter plus tard.",
    "Enter an environment-variable reference such as env:OPENWEBUI_API_KEY, not the API key itself. You can leave this field blank and connect the source later.": "Saisissez une référence de variable d’environnement telle que env:OPENWEBUI_API_KEY, et non la clé API elle-même. Vous pouvez laisser ce champ vide et connecter la source plus tard.",
  });
  Object.assign(catalogs["zh-CN"], {
    "Credential environment-variable reference (optional)": "凭据环境变量引用（可选）",
    "Enter env:OPENWEBUI_API_KEY—not the API key itself. You can also leave this blank and connect later.": "请输入 env:OPENWEBUI_API_KEY 之类的引用，而不是 API 密钥本身。也可以留空并稍后连接。",
    "Enter an environment-variable reference such as env:OPENWEBUI_API_KEY, not the API key itself. You can leave this field blank and connect the source later.": "请输入 env:OPENWEBUI_API_KEY 之类的环境变量引用，而不是 API 密钥本身。可以留空并稍后连接该数据源。",
  });
  Object.assign(catalogs.it, {
    "Credential environment-variable reference (optional)": "Riferimento alla variabile d’ambiente delle credenziali (facoltativo)",
    "Enter env:OPENWEBUI_API_KEY—not the API key itself. You can also leave this blank and connect later.": "Inserisci un riferimento come env:OPENWEBUI_API_KEY, non la chiave API stessa. Puoi anche lasciare vuoto il campo e connetterti in seguito.",
    "Enter an environment-variable reference such as env:OPENWEBUI_API_KEY, not the API key itself. You can leave this field blank and connect the source later.": "Inserisci un riferimento a una variabile d’ambiente come env:OPENWEBUI_API_KEY, non la chiave API stessa. Puoi lasciare vuoto il campo e collegare l’origine in seguito.",
  });

  Object.assign(catalogs.tr, {
    "RAGScanner service is running": "RAGScanner servisi çalışıyor", "Scans, reports, and scheduled work are available on this machine.": "Taramalar, raporlar ve zamanlanmış işler bu makinede kullanılabilir.", "View settings": "Ayarları görüntüle", "Set up this machine": "Bu makineyi kurun", "Complete four clear steps now. You can add or change sources later from the dashboard.": "Şimdi dört açık adımı tamamlayın. Kaynakları daha sonra dashboard'dan ekleyebilir veya değiştirebilirsiniz.", "Create the local account": "Yerel hesabı oluşturun", "Choose how you will work": "Nasıl çalışacağınızı seçin", "Connect data to scan": "Taranacak veriyi bağlayın", "Finish this machine": "Bu makinenin kurulumunu bitirin", "Your data stays on this machine.": "Verileriniz bu makinede kalır.", "Create the account used to open this machine-local dashboard.": "Bu makine-yerel dashboard'u açmak için kullanılacak hesabı oluşturun.", "Choose the interface that should open after setup.": "Kurulumdan sonra açılacak arayüzü seçin.", "Connect one source now, or leave its credential reference blank and connect later.": "Şimdi bir kaynak bağlayın veya kimlik bilgisi referansını boş bırakıp daha sonra bağlanın.", "Do not paste the API key.": "API anahtarını yapıştırmayın.", "Enter env:OPENWEBUI_API_KEY, or leave this blank and connect later.": "env:OPENWEBUI_API_KEY girin veya boş bırakıp daha sonra bağlanın.", "Nothing is saved until you finish setup. All settings remain editable from the dashboard.": "Kurulumu tamamlayana kadar hiçbir şey kaydedilmez. Tüm ayarlar dashboard'dan düzenlenebilir.",
  });
  Object.assign(catalogs.de, {
    "RAGScanner service is running": "Der RAGScanner-Dienst läuft", "Scans, reports, and scheduled work are available on this machine.": "Scans, Berichte und geplante Aufträge sind auf diesem Rechner verfügbar.", "View settings": "Einstellungen anzeigen", "Set up this machine": "Diesen Rechner einrichten", "Complete four clear steps now. You can add or change sources later from the dashboard.": "Schließen Sie jetzt vier übersichtliche Schritte ab. Quellen können später im Dashboard ergänzt oder geändert werden.", "Create the local account": "Lokales Konto erstellen", "Choose how you will work": "Arbeitsweise auswählen", "Connect data to scan": "Daten zum Scannen verbinden", "Finish this machine": "Einrichtung abschließen", "Your data stays on this machine.": "Ihre Daten bleiben auf diesem Rechner.", "Create the account used to open this machine-local dashboard.": "Erstellen Sie das Konto für dieses rechnerlokale Dashboard.", "Choose the interface that should open after setup.": "Wählen Sie die Oberfläche, die nach der Einrichtung geöffnet wird.", "Connect one source now, or leave its credential reference blank and connect later.": "Verbinden Sie jetzt eine Quelle oder lassen Sie die Referenz leer und verbinden Sie sie später.", "Do not paste the API key.": "API-Schlüssel nicht einfügen.", "Enter env:OPENWEBUI_API_KEY, or leave this blank and connect later.": "Geben Sie env:OPENWEBUI_API_KEY ein oder verbinden Sie die Quelle später.", "Nothing is saved until you finish setup. All settings remain editable from the dashboard.": "Bis zum Abschluss wird nichts gespeichert. Alle Einstellungen bleiben im Dashboard bearbeitbar.",
  });
  Object.assign(catalogs.fr, {
    "RAGScanner service is running": "Le service RAGScanner fonctionne", "Scans, reports, and scheduled work are available on this machine.": "Les analyses, rapports et tâches planifiées sont disponibles sur cette machine.", "View settings": "Voir les paramètres", "Set up this machine": "Configurer cette machine", "Complete four clear steps now. You can add or change sources later from the dashboard.": "Effectuez maintenant quatre étapes claires. Vous pourrez ajouter ou modifier les sources depuis le tableau de bord.", "Create the local account": "Créer le compte local", "Choose how you will work": "Choisir votre mode de travail", "Connect data to scan": "Connecter les données à analyser", "Finish this machine": "Terminer la configuration", "Your data stays on this machine.": "Vos données restent sur cette machine.", "Create the account used to open this machine-local dashboard.": "Créez le compte utilisé pour ouvrir ce tableau de bord local.", "Choose the interface that should open after setup.": "Choisissez l’interface à ouvrir après la configuration.", "Connect one source now, or leave its credential reference blank and connect later.": "Connectez une source maintenant ou laissez sa référence vide pour la connecter plus tard.", "Do not paste the API key.": "Ne collez pas la clé API.", "Enter env:OPENWEBUI_API_KEY, or leave this blank and connect later.": "Saisissez env:OPENWEBUI_API_KEY ou laissez ce champ vide pour vous connecter plus tard.", "Nothing is saved until you finish setup. All settings remain editable from the dashboard.": "Rien n’est enregistré avant la fin de la configuration. Tous les paramètres restent modifiables depuis le tableau de bord.",
  });
  Object.assign(catalogs["zh-CN"], {
    "RAGScanner service is running": "RAGScanner 服务正在运行", "Scans, reports, and scheduled work are available on this machine.": "此计算机上的扫描、报告和计划任务均可用。", "View settings": "查看设置", "Set up this machine": "设置此计算机", "Complete four clear steps now. You can add or change sources later from the dashboard.": "现在完成四个清晰步骤。之后可在仪表板中添加或更改数据源。", "Create the local account": "创建本地账户", "Choose how you will work": "选择工作方式", "Connect data to scan": "连接待扫描数据", "Finish this machine": "完成计算机设置", "Your data stays on this machine.": "您的数据保留在此计算机上。", "Create the account used to open this machine-local dashboard.": "创建用于打开本机仪表板的账户。", "Choose the interface that should open after setup.": "选择设置完成后打开的界面。", "Connect one source now, or leave its credential reference blank and connect later.": "立即连接一个数据源，或将凭据引用留空以便稍后连接。", "Do not paste the API key.": "请勿粘贴 API 密钥。", "Enter env:OPENWEBUI_API_KEY, or leave this blank and connect later.": "请输入 env:OPENWEBUI_API_KEY，或留空并稍后连接。", "Nothing is saved until you finish setup. All settings remain editable from the dashboard.": "完成设置前不会保存任何内容。所有设置之后仍可在仪表板中编辑。",
  });
  Object.assign(catalogs.it, {
    "RAGScanner service is running": "Il servizio RAGScanner è in esecuzione", "Scans, reports, and scheduled work are available on this machine.": "Analisi, rapporti e attività pianificate sono disponibili su questa macchina.", "View settings": "Visualizza impostazioni", "Set up this machine": "Configura questa macchina", "Complete four clear steps now. You can add or change sources later from the dashboard.": "Completa ora quattro passaggi chiari. Potrai aggiungere o modificare le origini dalla dashboard.", "Create the local account": "Crea l’account locale", "Choose how you will work": "Scegli come lavorare", "Connect data to scan": "Collega i dati da analizzare", "Finish this machine": "Completa la configurazione", "Your data stays on this machine.": "I tuoi dati rimangono su questa macchina.", "Create the account used to open this machine-local dashboard.": "Crea l’account usato per aprire questa dashboard locale.", "Choose the interface that should open after setup.": "Scegli l’interfaccia da aprire dopo la configurazione.", "Connect one source now, or leave its credential reference blank and connect later.": "Collega ora un’origine oppure lascia vuoto il riferimento e collegala in seguito.", "Do not paste the API key.": "Non incollare la chiave API.", "Enter env:OPENWEBUI_API_KEY, or leave this blank and connect later.": "Inserisci env:OPENWEBUI_API_KEY oppure lascia vuoto e collegati in seguito.", "Nothing is saved until you finish setup. All settings remain editable from the dashboard.": "Nulla viene salvato finché non completi la configurazione. Tutte le impostazioni restano modificabili dalla dashboard.",
  });

  Object.assign(catalogs.tr, {
    "The passphrase is stored only as a local memory-hard hash.": "Parola yalnızca yerel ve bellek-zorlu bir özet olarak saklanır.", "Manage sources, jobs, and reports in your browser": "Kaynakları, işleri ve raporları tarayıcınızdan yönetin", "Configure and run scans from the terminal": "Taramaları terminalden yapılandırın ve çalıştırın", "Discover a local service or enter its address": "Yerel bir servisi bulun veya adresini girin", "Discover containers, Kubernetes services, vector stores, and localhost endpoints": "Container'ları, Kubernetes servislerini, vektör depolarını ve localhost uç noktalarını bulun", "Scan a file or folder without saving a source profile": "Kaynak profili kaydetmeden bir dosya veya klasörü tarayın", "Discovery reads bounded local metadata only. Content is accessed when a scan job starts.": "Keşif yalnızca sınırlandırılmış yerel metadatayı okur. İçeriğe bir tarama işi başladığında erişilir.", "Product knowledge": "Ürün bilgisi",
  });
  Object.assign(catalogs.de, {
    "The passphrase is stored only as a local memory-hard hash.": "Die Passphrase wird nur als lokaler speicherharter Hash gespeichert.", "Manage sources, jobs, and reports in your browser": "Quellen, Aufträge und Berichte im Browser verwalten", "Configure and run scans from the terminal": "Scans im Terminal konfigurieren und ausführen", "Discover a local service or enter its address": "Lokalen Dienst erkennen oder Adresse eingeben", "Discover containers, Kubernetes services, vector stores, and localhost endpoints": "Container, Kubernetes-Dienste, Vektorspeicher und localhost-Endpunkte erkennen", "Scan a file or folder without saving a source profile": "Datei oder Ordner ohne Quellenprofil scannen", "Discovery reads bounded local metadata only. Content is accessed when a scan job starts.": "Die Erkennung liest nur begrenzte lokale Metadaten. Inhalte werden erst beim Start eines Scans gelesen.", "Product knowledge": "Produktwissen",
  });
  Object.assign(catalogs.fr, {
    "The passphrase is stored only as a local memory-hard hash.": "La phrase secrète est stockée uniquement sous forme de hachage local résistant en mémoire.", "Manage sources, jobs, and reports in your browser": "Gérez les sources, tâches et rapports dans votre navigateur", "Configure and run scans from the terminal": "Configurez et lancez les analyses depuis le terminal", "Discover a local service or enter its address": "Détectez un service local ou saisissez son adresse", "Discover containers, Kubernetes services, vector stores, and localhost endpoints": "Détectez conteneurs, services Kubernetes, bases vectorielles et points localhost", "Scan a file or folder without saving a source profile": "Analysez un fichier ou dossier sans enregistrer de profil", "Discovery reads bounded local metadata only. Content is accessed when a scan job starts.": "La découverte lit uniquement des métadonnées locales limitées. Le contenu est lu au démarrage d’une analyse.", "Product knowledge": "Connaissances produit",
  });
  Object.assign(catalogs["zh-CN"], {
    "The passphrase is stored only as a local memory-hard hash.": "密码短语仅以本地内存强化哈希形式存储。", "Manage sources, jobs, and reports in your browser": "在浏览器中管理数据源、任务和报告", "Configure and run scans from the terminal": "从终端配置并运行扫描", "Discover a local service or enter its address": "发现本地服务或输入其地址", "Discover containers, Kubernetes services, vector stores, and localhost endpoints": "发现容器、Kubernetes 服务、向量数据库和 localhost 端点", "Scan a file or folder without saving a source profile": "扫描文件或文件夹而不保存数据源配置", "Discovery reads bounded local metadata only. Content is accessed when a scan job starts.": "发现过程仅读取有限的本地元数据。内容只在扫描任务启动时访问。", "Product knowledge": "产品知识",
  });
  Object.assign(catalogs.it, {
    "The passphrase is stored only as a local memory-hard hash.": "La passphrase viene memorizzata solo come hash locale resistente alla memoria.", "Manage sources, jobs, and reports in your browser": "Gestisci origini, attività e rapporti nel browser", "Configure and run scans from the terminal": "Configura ed esegui le analisi dal terminale", "Discover a local service or enter its address": "Rileva un servizio locale o inserisci il suo indirizzo", "Discover containers, Kubernetes services, vector stores, and localhost endpoints": "Rileva container, servizi Kubernetes, database vettoriali ed endpoint localhost", "Scan a file or folder without saving a source profile": "Analizza un file o una cartella senza salvare un profilo", "Discovery reads bounded local metadata only. Content is accessed when a scan job starts.": "Il rilevamento legge solo metadati locali limitati. Il contenuto viene letto quando parte un’analisi.", "Product knowledge": "Conoscenza prodotto",
  });

  Object.assign(catalogs.tr, {
    "Connect the places that contain knowledge you want RAGScanner to assess.": "RAGScanner'ın değerlendirmesini istediğiniz bilgileri içeren ortamları bağlayın.", "Find sources automatically": "Kaynakları otomatik bul", "Add source": "Kaynak ekle", "Ready to scan": "Taramaya hazır", "API key needed": "API anahtarı gerekli", "Detected only": "Yalnızca algılandı", "Connect": "Bağlan", "Add a source": "Kaynak ekle", "Environment": "Ortam", "Local file or folder": "Yerel dosya veya klasör", "Connection name": "Bağlantı adı", "Address or path": "Adres veya yol", "Authentication": "Kimlik doğrulama", "API key": "API anahtarı", "Paste the API key": "API anahtarını yapıştırın", "No authentication": "Kimlik doğrulama yok", "Environment variable": "Ortam değişkeni", "Advanced settings": "Gelişmiş ayarlar", "Add later": "Daha sonra ekle", "Scan jobs": "Tarama işleri", "A scan job tells RAGScanner what source to scan. The machine service runs it and saves the report.": "Tarama işi, RAGScanner'a hangi kaynağı tarayacağını söyler. Makine servisi işi çalıştırır ve raporu kaydeder.", "Create scan job": "Tarama işi oluştur", "New scan": "Yeni tarama", "Select source": "Kaynak seç", "Source": "Kaynak", "Enter a local path manually": "Yerel yolu elle gir", "Complete this connection": "Bu bağlantıyı tamamla", "This source needs an API key before RAGScanner can list its knowledge bases.": "RAGScanner'ın bilgi tabanlarını listeleyebilmesi için bu kaynağa API anahtarı gerekir.", "Use an environment variable instead": "Bunun yerine ortam değişkeni kullan", "Test and continue": "Test et ve devam et", "Define scope": "Kapsamı belirle", "OpenWebUI address": "OpenWebUI adresi", "Skip for now": "Şimdilik geç", "Address": "Adres",
  });
  Object.assign(catalogs.de, {
    "Connect the places that contain knowledge you want RAGScanner to assess.": "Verbinden Sie die Orte mit dem Wissen, das RAGScanner prüfen soll.", "Find sources automatically": "Quellen automatisch finden", "Add source": "Quelle hinzufügen", "Ready to scan": "Scanbereit", "API key needed": "API-Schlüssel erforderlich", "Detected only": "Nur erkannt", "Connect": "Verbinden", "Add a source": "Quelle hinzufügen", "Environment": "Umgebung", "Local file or folder": "Lokale Datei oder Ordner", "Connection name": "Verbindungsname", "Address or path": "Adresse oder Pfad", "Authentication": "Authentifizierung", "API key": "API-Schlüssel", "Paste the API key": "API-Schlüssel einfügen", "No authentication": "Keine Authentifizierung", "Environment variable": "Umgebungsvariable", "Advanced settings": "Erweiterte Einstellungen", "Add later": "Später hinzufügen", "Scan jobs": "Scanaufträge", "A scan job tells RAGScanner what source to scan. The machine service runs it and saves the report.": "Ein Scanauftrag legt fest, welche Quelle RAGScanner scannt. Der Rechnerdienst führt ihn aus und speichert den Bericht.", "Create scan job": "Scanauftrag erstellen", "New scan": "Neuer Scan", "Select source": "Quelle auswählen", "Source": "Quelle", "Enter a local path manually": "Lokalen Pfad manuell eingeben", "Complete this connection": "Verbindung vervollständigen", "This source needs an API key before RAGScanner can list its knowledge bases.": "Diese Quelle benötigt einen API-Schlüssel, bevor RAGScanner ihre Wissensdatenbanken auflisten kann.", "Use an environment variable instead": "Stattdessen Umgebungsvariable verwenden", "Test and continue": "Testen und fortfahren", "Define scope": "Umfang festlegen", "OpenWebUI address": "OpenWebUI-Adresse", "Skip for now": "Vorerst überspringen", "Address": "Adresse",
  });
  Object.assign(catalogs.fr, {
    "Connect the places that contain knowledge you want RAGScanner to assess.": "Connectez les emplacements contenant les connaissances que RAGScanner doit évaluer.", "Find sources automatically": "Trouver les sources automatiquement", "Add source": "Ajouter une source", "Ready to scan": "Prête à analyser", "API key needed": "Clé API requise", "Detected only": "Détectée uniquement", "Connect": "Connecter", "Add a source": "Ajouter une source", "Environment": "Environnement", "Local file or folder": "Fichier ou dossier local", "Connection name": "Nom de la connexion", "Address or path": "Adresse ou chemin", "Authentication": "Authentification", "API key": "Clé API", "Paste the API key": "Collez la clé API", "No authentication": "Aucune authentification", "Environment variable": "Variable d’environnement", "Advanced settings": "Paramètres avancés", "Add later": "Ajouter plus tard", "Scan jobs": "Tâches d’analyse", "A scan job tells RAGScanner what source to scan. The machine service runs it and saves the report.": "Une tâche indique à RAGScanner quelle source analyser. Le service de la machine l’exécute et enregistre le rapport.", "Create scan job": "Créer une tâche d’analyse", "New scan": "Nouvelle analyse", "Select source": "Sélectionner la source", "Source": "Source", "Enter a local path manually": "Saisir un chemin local", "Complete this connection": "Terminer cette connexion", "This source needs an API key before RAGScanner can list its knowledge bases.": "Cette source nécessite une clé API avant que RAGScanner puisse répertorier ses bases de connaissances.", "Use an environment variable instead": "Utiliser plutôt une variable d’environnement", "Test and continue": "Tester et continuer", "Define scope": "Définir le périmètre", "OpenWebUI address": "Adresse OpenWebUI", "Skip for now": "Ignorer pour l’instant", "Address": "Adresse",
  });
  Object.assign(catalogs["zh-CN"], {
    "Connect the places that contain knowledge you want RAGScanner to assess.": "连接包含待评估知识的位置。", "Find sources automatically": "自动查找数据源", "Add source": "添加数据源", "Ready to scan": "可扫描", "API key needed": "需要 API 密钥", "Detected only": "仅检测到", "Connect": "连接", "Add a source": "添加数据源", "Environment": "环境", "Local file or folder": "本地文件或文件夹", "Connection name": "连接名称", "Address or path": "地址或路径", "Authentication": "身份验证", "API key": "API 密钥", "Paste the API key": "粘贴 API 密钥", "No authentication": "无需身份验证", "Environment variable": "环境变量", "Advanced settings": "高级设置", "Add later": "稍后添加", "Scan jobs": "扫描任务", "A scan job tells RAGScanner what source to scan. The machine service runs it and saves the report.": "扫描任务告诉 RAGScanner 要扫描哪个数据源；本机服务会运行任务并保存报告。", "Create scan job": "创建扫描任务", "New scan": "新扫描", "Select source": "选择数据源", "Source": "数据源", "Enter a local path manually": "手动输入本地路径", "Complete this connection": "完成此连接", "This source needs an API key before RAGScanner can list its knowledge bases.": "RAGScanner 需要此数据源的 API 密钥才能列出知识库。", "Use an environment variable instead": "改用环境变量", "Test and continue": "测试并继续", "Define scope": "定义范围", "OpenWebUI address": "OpenWebUI 地址", "Skip for now": "暂时跳过", "Address": "地址",
  });
  Object.assign(catalogs.it, {
    "Connect the places that contain knowledge you want RAGScanner to assess.": "Collega le posizioni che contengono le conoscenze da valutare.", "Find sources automatically": "Trova origini automaticamente", "Add source": "Aggiungi origine", "Ready to scan": "Pronta per l’analisi", "API key needed": "Chiave API necessaria", "Detected only": "Solo rilevata", "Connect": "Connetti", "Add a source": "Aggiungi un’origine", "Environment": "Ambiente", "Local file or folder": "File o cartella locale", "Connection name": "Nome connessione", "Address or path": "Indirizzo o percorso", "Authentication": "Autenticazione", "API key": "Chiave API", "Paste the API key": "Incolla la chiave API", "No authentication": "Nessuna autenticazione", "Environment variable": "Variabile d’ambiente", "Advanced settings": "Impostazioni avanzate", "Add later": "Aggiungi più tardi", "Scan jobs": "Attività di analisi", "A scan job tells RAGScanner what source to scan. The machine service runs it and saves the report.": "Un’attività indica a RAGScanner quale origine analizzare. Il servizio della macchina la esegue e salva il rapporto.", "Create scan job": "Crea attività di analisi", "New scan": "Nuova analisi", "Select source": "Seleziona origine", "Source": "Origine", "Enter a local path manually": "Inserisci un percorso locale", "Complete this connection": "Completa la connessione", "This source needs an API key before RAGScanner can list its knowledge bases.": "Questa origine richiede una chiave API prima che RAGScanner possa elencarne le knowledge base.", "Use an environment variable instead": "Usa invece una variabile d’ambiente", "Test and continue": "Verifica e continua", "Define scope": "Definisci ambito", "OpenWebUI address": "Indirizzo OpenWebUI", "Skip for now": "Salta per ora", "Address": "Indirizzo",
  });

  Object.assign(catalogs.tr, {
    "Detected models": "Bulunan modeller", "Choose a detected model": "Bulunan bir modeli seçin", "Advanced credential reference": "Gelişmiş kimlik bilgisi referansı", "Use an env: reference for unattended jobs across service restarts.": "Servis yeniden başlatmalarında gözetimsiz işler için env: referansı kullanın.", "Job activity logs": "İş etkinlik logları", "Safe status and error codes from the latest job state. Secret values and raw provider responses are never shown.": "Son iş durumundaki güvenli durum ve hata kodları. Gizli değerler ve ham sağlayıcı yanıtları asla gösterilmez.", "Live": "Canlı", "Update unavailable": "Güncelleme kullanılamıyor", "No job activity yet.": "Henüz iş etkinliği yok.", "The job is queued and waiting for the Host Service worker.": "İş kuyrukta ve Host Service worker'ını bekliyor.", "The deterministic scan is running.": "Deterministik tarama çalışıyor.", "The deterministic scan is complete and AI analysis is running.": "Deterministik tarama tamamlandı ve AI analizi çalışıyor.", "The report is being validated and saved.": "Rapor doğrulanıyor ve kaydediliyor.", "The scan completed and its report was saved.": "Tarama tamamlandı ve rapor kaydedildi.", "The scan and AI-assisted report analysis completed successfully.": "Tarama ve AI destekli rapor analizi başarıyla tamamlandı.", "The job was cancelled.": "İş iptal edildi.", "Cancellation was requested and will be applied at the next safe checkpoint.": "İptal istendi ve sonraki güvenli kontrol noktasında uygulanacak.",
  });
  Object.assign(catalogs.de, {
    "Detected models": "Erkannte Modelle", "Choose a detected model": "Erkanntes Modell auswählen", "Advanced credential reference": "Erweiterte Anmeldedaten-Referenz", "Use an env: reference for unattended jobs across service restarts.": "Verwenden Sie für unbeaufsichtigte Aufträge über Dienstneustarts hinweg eine env:-Referenz.", "Job activity logs": "Auftragsaktivitätsprotokolle", "Safe status and error codes from the latest job state. Secret values and raw provider responses are never shown.": "Sichere Status- und Fehlercodes des letzten Auftragszustands. Geheimnisse und rohe Anbieterantworten werden nie angezeigt.", "Live": "Live", "Update unavailable": "Aktualisierung nicht verfügbar", "No job activity yet.": "Noch keine Auftragsaktivität.", "The job is queued and waiting for the Host Service worker.": "Der Auftrag wartet in der Warteschlange auf den Host-Service-Worker.", "The deterministic scan is running.": "Der deterministische Scan läuft.", "The deterministic scan is complete and AI analysis is running.": "Der deterministische Scan ist abgeschlossen; die KI-Analyse läuft.", "The report is being validated and saved.": "Der Bericht wird validiert und gespeichert.", "The scan completed and its report was saved.": "Der Scan wurde abgeschlossen und der Bericht gespeichert.", "The scan and AI-assisted report analysis completed successfully.": "Scan und KI-gestützte Berichtsanalyse wurden erfolgreich abgeschlossen.", "The job was cancelled.": "Der Auftrag wurde abgebrochen.", "Cancellation was requested and will be applied at the next safe checkpoint.": "Der Abbruch wurde angefordert und wird am nächsten sicheren Prüfpunkt angewendet.",
  });
  Object.assign(catalogs.fr, {
    "Detected models": "Modèles détectés", "Choose a detected model": "Choisir un modèle détecté", "Advanced credential reference": "Référence d’identifiants avancée", "Use an env: reference for unattended jobs across service restarts.": "Utilisez une référence env: pour les tâches sans surveillance après redémarrage du service.", "Job activity logs": "Journaux d’activité des tâches", "Safe status and error codes from the latest job state. Secret values and raw provider responses are never shown.": "États et codes d’erreur sûrs du dernier état de la tâche. Les secrets et réponses brutes ne sont jamais affichés.", "Live": "En direct", "Update unavailable": "Mise à jour indisponible", "No job activity yet.": "Aucune activité de tâche.", "The job is queued and waiting for the Host Service worker.": "La tâche est en file d’attente du worker Host Service.", "The deterministic scan is running.": "L’analyse déterministe est en cours.", "The deterministic scan is complete and AI analysis is running.": "L’analyse déterministe est terminée et l’analyse IA est en cours.", "The report is being validated and saved.": "Le rapport est validé et enregistré.", "The scan completed and its report was saved.": "L’analyse est terminée et son rapport a été enregistré.", "The scan and AI-assisted report analysis completed successfully.": "L’analyse et l’interprétation IA du rapport ont réussi.", "The job was cancelled.": "La tâche a été annulée.", "Cancellation was requested and will be applied at the next safe checkpoint.": "L’annulation a été demandée et sera appliquée au prochain point de contrôle sûr.",
  });
  Object.assign(catalogs["zh-CN"], {
    "Detected models": "检测到的模型", "Choose a detected model": "选择检测到的模型", "Advanced credential reference": "高级凭据引用", "Use an env: reference for unattended jobs across service restarts.": "对于跨服务重启的无人值守任务，请使用 env: 引用。", "Job activity logs": "任务活动日志", "Safe status and error codes from the latest job state. Secret values and raw provider responses are never shown.": "显示最新任务状态中的安全状态码和错误码，绝不显示密钥或提供商原始响应。", "Live": "实时", "Update unavailable": "更新不可用", "No job activity yet.": "暂无任务活动。", "The job is queued and waiting for the Host Service worker.": "任务已排队，正在等待 Host Service worker。", "The deterministic scan is running.": "确定性扫描正在运行。", "The deterministic scan is complete and AI analysis is running.": "确定性扫描已完成，AI 分析正在运行。", "The report is being validated and saved.": "正在验证并保存报告。", "The scan completed and its report was saved.": "扫描已完成并保存报告。", "The scan and AI-assisted report analysis completed successfully.": "扫描和 AI 辅助报告分析已成功完成。", "The job was cancelled.": "任务已取消。", "Cancellation was requested and will be applied at the next safe checkpoint.": "已请求取消，将在下一个安全检查点执行。",
  });
  Object.assign(catalogs.it, {
    "Detected models": "Modelli rilevati", "Choose a detected model": "Scegli un modello rilevato", "Advanced credential reference": "Riferimento credenziali avanzato", "Use an env: reference for unattended jobs across service restarts.": "Usa un riferimento env: per attività non presidiate tra i riavvii del servizio.", "Job activity logs": "Log attività dei processi", "Safe status and error codes from the latest job state. Secret values and raw provider responses are never shown.": "Stati e codici di errore sicuri dell’ultimo stato. Segreti e risposte grezze del provider non vengono mai mostrati.", "Live": "In tempo reale", "Update unavailable": "Aggiornamento non disponibile", "No job activity yet.": "Nessuna attività disponibile.", "The job is queued and waiting for the Host Service worker.": "L’attività è in coda in attesa del worker Host Service.", "The deterministic scan is running.": "La scansione deterministica è in esecuzione.", "The deterministic scan is complete and AI analysis is running.": "La scansione deterministica è completa e l’analisi AI è in esecuzione.", "The report is being validated and saved.": "Il rapporto viene convalidato e salvato.", "The scan completed and its report was saved.": "La scansione è completa e il rapporto è stato salvato.", "The scan and AI-assisted report analysis completed successfully.": "Scansione e analisi AI del rapporto completate correttamente.", "The job was cancelled.": "L’attività è stata annullata.", "Cancellation was requested and will be applied at the next safe checkpoint.": "L’annullamento è stato richiesto e verrà applicato al prossimo checkpoint sicuro.",
  });

  const cookieLocale = document.cookie.split("; ").find((item) => item.startsWith("ragscanner_locale="))?.split("=")[1];
  const browserLocale = navigator.language === "zh-CN" || navigator.language === "zh-SG" ? "zh-CN" : navigator.language.split("-")[0];
  const locale = languages[cookieLocale] ? cookieLocale : (languages[browserLocale] ? browserLocale : "en");
  const catalog = catalogs[locale] || {};
  const translate = (value) => {
    if (catalog[value]) return catalog[value];
    const viewAll = value.match(/^View all (\d+)$/);
    if (viewAll) return `${catalog["View all"] || "View all"} ${viewAll[1]}`;
    const enabledProfiles = value.match(/^(\d+) enabled profile\(s\)$/);
    if (enabledProfiles) return `${enabledProfiles[1]} ${catalog["enabled profile(s)"] || "enabled profile(s)"}`;
    const total = value.match(/^(\d+) total$/);
    if (total) return `${total[1]} ${catalog.total || "total"}`;
    const sourceStatus = value.match(/^(.+) · (API key needed|Ready|Detected only)$/);
    if (sourceStatus) return `${sourceStatus[1]} · ${catalog[sourceStatus[2]] || sourceStatus[2]}`;
    return value;
  };
  window.ragscannerTranslate = translate;
  document.documentElement.lang = languages[locale].locale;

  const translateTree = (root) => {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
      if (["SCRIPT", "STYLE", "CODE"].includes(node.parentElement?.tagName)) return;
      const value = node.nodeValue || "";
      const trimmed = value.trim();
      const translated = translate(trimmed);
      if (trimmed && translated !== trimmed) node.nodeValue = value.replace(trimmed, translated);
    });
    root.querySelectorAll("[placeholder],[aria-label],[title]").forEach((element) => {
      ["placeholder", "aria-label", "title"].forEach((attribute) => {
        const value = element.getAttribute(attribute);
        if (value) element.setAttribute(attribute, translate(value));
      });
    });
  };

  document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll("[data-language-picker]").forEach((picker) => {
      picker.value = locale;
      picker.addEventListener("change", () => {
        document.cookie = `ragscanner_locale=${encodeURIComponent(picker.value)}; Path=/; SameSite=Strict; Max-Age=31536000`;
        window.location.reload();
      });
    });
    translateTree(document.body);
  });
})();
